name: first_flutter
description: "A new Flutter project."

publish_to: 'none'


version: 7.0.0+7

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  change_app_package_name: ^1.5.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  video_player: ^2.10.1
  file_picker: ^10.3.7
  dart_nats: ^0.6.0
  google_maps_flutter: ^2.14.0
  intl: ^0.20.2
  google_sign_in: ^6.2.1
  firebase_auth: ^6.1.2
  flutter_screenutil: ^5.9.3
  http_parser: ^4.1.2
  flutter_background_service: ^5.1.0
  permission_handler: ^12.0.1
  flutter_polyline_points: ^3.1.0
  flutter_html: ^3.0.0
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  pdf: ^3.11.3
  url_launcher: ^6.3.2
  app_settings: ^7.0.0
  flutter_riverpod: ^3.0.3
  sms_autofill: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/backGroundImg/loginBg.png
    - assets/constantImg/googleBtn.png
    - assets/constantImg/phoneImg.png
    - assets/images/
    - assets/icons/
    - assets/moyosplash.mp4


  fonts:
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoExtraBold
      fonts:
        - asset: assets/fonts/Roboto-ExtraBold.ttf
    - family: RobotoExtraBoldItalic
      fonts:
        - asset: assets/fonts/Roboto-ExtraBoldItalic.ttf
          style: italic
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoExtraLight
      fonts:
        - asset: assets/fonts/Roboto-ExtraLight.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoSemiBold
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
